# Generated by Django 4.1.8 on 2023-05-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BusFrom', models.CharField(max_length=30)),
                ('BusTo', models.CharField(max_length=30)),
                ('BusName', models.CharField(max_length=20)),
                ('BusType', models.CharField(max_length=20)),
                ('Arrival', models.CharField(default=1, max_length=20)),
                ('Departure', models.CharField(default=5, max_length=20)),
                ('BusFee', models.PositiveIntegerField(default=400)),
                ('Availability', models.PositiveIntegerField(default=27)),
            ],
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
    ]
