# Generated by Django 4.1.8 on 2023-05-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_register_bookedid_register_bookedticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BusFee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='bookedId',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='bookedTicket',
            field=models.PositiveIntegerField(),
        ),
    ]
