# Generated by Django 4.1.8 on 2023-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_booking_busfee_alter_register_bookedid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='bookedId',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='bookedTicket',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
